default_platform(:android)

platform :android do
  desc "lane for andriod firebase app distribution "
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk"
    firebase_app_distribution(
    app: "1:817879246720:android:6ae66bd63fc18ec9824365",
    apk_path: "../build/app/outputs/apk/release/app-release.apk",
    testers: "mamdouhanahamada@gmail.com,ziadmagdy718@gmail.com",
    release_notes: "adding notification feature datasource -> repo -> cubit but It's still without ui , UI will be the next step",
    firebase_cli_token: ENV["FIREBASE_TOKEN"]
  )
  end
end