default_platform(:android)

platform :android do
  desc "lane for andriod firebase app distribution "
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk"
    firebase_app_distribution(
    app: "1:817879246720:android:6ae66bd63fc18ec9824365",
    apk_path: "../build/app/outputs/apk/release/app-release.apk",
    testers: "mamdouhanahamada@gmail.com,3mr3laa120@gmail.com",
    release_notes: "test the application but loging is only works with google so try the app and gimme a feedback",
    firebase_cli_token: ENV["FIREBASE_TOKEN"]
  )
  end
end